---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: gam-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
      owner: maplelabs
  template:
    metadata:
      labels:
        app: hello-nginx
        owner: maplelabs
    spec:
      containers:
      - name: hello-nginx
        image: nginx:1.21.6
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
